CREATE DATABASE user_data
WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

CREATE TABLE if not exists public.role
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                             NOT NULL,
    active BOOLEAN,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

ALTER TABLE public.role
    ADD CONSTRAINT  uc_role_name UNIQUE (name);

CREATE TABLE if not exists public.user_app
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                             NOT NULL,
    password      VARCHAR(255),
    name          VARCHAR(255)                             NOT NULL,
    last_name     VARCHAR(255)                             NOT NULL,
    email         VARCHAR(255)                             NOT NULL,
    role_id       INTEGER,
    active        BOOLEAN,
    update_time   TIMESTAMP WITHOUT TIME ZONE,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_app PRIMARY KEY (id)
);

ALTER TABLE public.user_app
    ADD CONSTRAINT uc_user_app_username UNIQUE (username);

ALTER TABLE public.user_app
    ADD CONSTRAINT FK_USER_APP_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

insert into role (id, name, active) values (1, 'Admin', true);
insert into role (id, name, active) values (2, 'Client', true );
insert into role (id, name, active) values (3, 'Employee', true );
insert into user_app (id, name, email, last_name, password, username, role_id) values ( 1, 'Alicia', 'alicruz0703@gmail.com', 'Cruz', '$2a$10$XUZRhDaN7U2oNUMZtN1wNOzPL2nUptG0K29dxXmAFH9eXbGCOrTKS', 'ali00', 1);
