insert into product (id ,name, availability) values (1, 'Camera', true);
insert into product (id, name, availability) values (2, 'Tripo', true);
insert into product (id, name, availability) values (3, 'Lights', true);
insert into product (id, name, availability) values (4, 'Video Camera', true);
insert into product (id, name, availability) values (5, 'Decoration', true);
insert into event (id, name, price) values (1, 'Pre-Wedding', 1000);
insert into event_products (event_id, products_id) values (1,1);
insert into event_products (event_id, products_id) values (1,4);
insert into event (id, name, price) values (2, 'Wedding', 5000);
insert into event_products (event_id, products_id) values (2,1);
insert into event_products (event_id, products_id) values (2,4);
insert into event_products (event_id, products_id) values (2,3);
insert into event_products (event_id, products_id) values (2,2);
insert into event_products (event_id, products_id) values (2,5);
insert into event (id, name, price) values (3, 'Birthday', 3000);
insert into event_products (event_id, products_id) values (3,1);
insert into event_products (event_id, products_id) values (3,3);
insert into event_products (event_id, products_id) values (3,5);
insert into event (id, name, price) values (4, 'Event Video', 4000);
insert into event_products (event_id, products_id) values (4,4);
insert into event_products (event_id, products_id) values (4,2);
